# Generated by Django 3.2.8 on 2021-11-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven', '0002_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='resident',
            name='short_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
